server:
  port: 80




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost




spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-gateway-service
          uri: lb://ms-gateway-service
          predicates:
            - Path=/gateway/**
